kind: TridentMirrorRelationship
apiVersion: trident.netapp.io/v1
metadata:
  name: assets-share
spec:
  state: promoted
---
kind: TridentMirrorRelationship
apiVersion: trident.netapp.io/v1
metadata:
  name: data-catalog-mysql-0
spec:
  state: promoted
---
kind: TridentMirrorRelationship
apiVersion: trident.netapp.io/v1
metadata:
  name: data-orders-mysql-0
spec:
  state: promoted
---
kind: TridentMirrorRelationship
apiVersion: trident.netapp.io/v1
metadata:
  name: data-orders-rabbitmq-0
spec:
  state: promoted
