apiVersion: batch/v1
kind: Job
metadata:
  name: peer-clusters
  namespace: trident
spec:
  template:
    spec:
      serviceAccountName: trident-controller
      containers:
      - name: python
        image: 139763910815.dkr.ecr.us-east-1.amazonaws.com/fsxn/ontap-peer:latest
        volumeMounts:
          - name: parms
            mountPath: /usr/src/app/parms
      restartPolicy: Never
      volumes:
        - name: parms
          configMap:
            name: peer-parms