kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: assets-share
  annotations:
    trident.netapp.io/mirrorRelationship: assets-share
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: trident-csi-nas
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-catalog-mysql-0
  annotations:
    trident.netapp.io/mirrorRelationship: data-catalog-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: trident-csi-san
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-orders-mysql-0
  annotations:
    trident.netapp.io/mirrorRelationship: data-orders-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: trident-csi-san
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-orders-rabbitmq-0
  annotations:
    trident.netapp.io/mirrorRelationship: data-orders-rabbitmq-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: trident-csi-san