apiVersion: v1
kind: Pod
metadata:
  name: sshpod
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache openssh
        sleep 60m
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
